// ============================================================
// services/mail.js — Email Service (Resend API)
// ============================================================

const { Resend } = require('resend');

// Initialize Resend
const resend = new Resend(process.env.RESEND_API_KEY);

// ── Helper: Format numbers (123456 → 123,456)
function formatViews(num) {
  if (!num) return '0';
  return Number(num).toLocaleString('en-US');
}

// ── Helper: Format date
function formatDate(isoString) {
  const date = new Date(isoString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

// ── Build HTML email
function buildEmailHTML(videos) {
  return `
    <div style="font-family: Arial; padding:20px;">
      <h2>🚀 Top 10 AI YouTube Videos</h2>
      <p>Auto-generated by your AI Agent</p>
      <ul>
        ${videos.map((v, i) => `
          <li style="margin-bottom:10px;">
            <b>#${i + 1}</b> ${v.title}<br/>
            👁 ${formatViews(v.viewCount)} views | 📅 ${formatDate(v.publishedAt)}<br/>
            <a href="${v.videoUrl}" target="_blank">Watch</a>
          </li>
        `).join('')}
      </ul>
    </div>
  `;
}

// ── Main function
async function sendEmail(videos) {
  try {
    if (!process.env.RESEND_API_KEY) {
      throw new Error("RESEND_API_KEY missing in .env");
    }

    console.log("📧 Sending email...");

    const response = await resend.emails.send({
      from: 'onboarding@resend.dev', // default working sender
      to: process.env.RECIPIENT_EMAIL,
      subject: '🤖 Top 10 AI YouTube Videos',
      html: buildEmailHTML(videos),
    });

    console.log("✅ Email sent successfully!");
    console.log("📨 Response:", response);

    return response;

  } catch (error) {
    console.error("❌ Email Error:", error.message);
  }
}

module.exports = { sendEmail };